# Generated by Django 5.0.1 on 2024-06-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projector_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
