# Generated by Django 5.0.1 on 2024-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projector_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../projector_managemnt/static/assets'),
        ),
    ]
